# nginx proxy address - http://172.17.0.1:25600

x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  komga:
    image: gotson/komga:latest
    container_name: komga-app
    restart: unless-stopped
    logging: *default-logging
    networks:
      - komga
    ports:
      - "25600:25600"
    environment:
      TZ: ${TZ:-America/New_York}
      PUID: ${SERVICE_USER:-1000}
      PGID: ${SERVICE_GROUP:-1000}
    volumes:
      - ./rootfs/config/komga:/config
      - ./rootfs/data/komga:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:25600"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  komga:
    external: false
